### ISSUE TITLE
Distributed computation (like ClusterSharding)

### ISSUE THREAD

**Issue by twillouer** [opentracing-contrib/java-akka#8]
Hi,

I think 'location transparency' is not working with your design.

In case of the received actor is not localized on same sender's jvm, TracedMessage will not work.

In my opinion, we need to have span "forward" but not the same span.
Or use a TracedDistributedMessage who work with this behavior (and you keep TracedMessage for the same JVM) ?
Or the TracedMessage must detect than this is not the same JVM and use both behavior (same span on same jvm, forward span when changing) ?

What do you think ?

**Comment by malafeev** [comment]
I agree, but it's up to you @twillouer to figure out best solution.
